# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-28 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('ra', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('rfid', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoal.Departamento')),
            ],
        ),
    ]
