# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-03 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0002_auto_20170803_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='pessoal.Empresa'),
            preserve_default=False,
        ),
    ]
