# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-04 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_funcionario_permanencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permanencia',
            name='saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
