# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-04 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20170504_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='ra',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
