# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-04 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20170504_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permanencia',
            name='entrada',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'entrada'),
        ),
        migrations.AlterField(
            model_name='permanencia',
            name='saida',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'saida'),
        ),
    ]
