# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-10 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20170504_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='permanencia',
            name='reposicao',
            field=models.BooleanField(default=False),
        ),
    ]
