# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-29 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permanencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField(auto_now_add=True, verbose_name='entrada')),
                ('saida', models.DateTimeField(blank=True, null=True, verbose_name='saida')),
                ('reposicao', models.BooleanField(default=False)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanencias', to='pessoal.Funcionario')),
            ],
        ),
    ]
